apiVersion: v1
kind: Service
metadata:
  name: ingress-controller
  labels:
    app: ingress-controller
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: ingress-controller
  type: LoadBalancer
